blank_issues_enabled: false
contact_links:
  - name: 📣 Discussion Board
    url: https://github.com/SEVENNetworks/AdClearContentBlocker/discussions
    about: Please suggest new features or ask questions here! 💬